load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "storage_proto",
    srcs = [
        "storage.proto",
        "storage_resources.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//google/api:api_proto",
        "//google/iam/v1:v1_proto",
        "//google/storage/v1:v1_proto",
        "@com_google_protobuf//:field_mask_proto",
        "@com_google_protobuf//:timestamp_proto",
        "@com_google_protobuf//:wrappers_proto",
    ],
)

go_proto_library(
    name = "storage_go_proto",
    importpath = "google.golang.org/genproto/googleapis/storage/v1",
    proto = ":storage_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//google/api:field_behavior_proto",
        "//google/iam/v1:iam_policy_proto",
        "//google/storage/v1:storage_resources_proto",
    ],
)

go_library(
    name = "storage",
    embed = [":storage_go_proto"],
    importpath = "google.golang.org/genproto/googleapis/storage/v1",
    visibility = ["//visibility:public"],
)
