load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "iampb_proto",
    srcs = [
        "iam_policy.proto",
        "options.proto",
        "policy.proto",
        "resource_policy_member.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//google/api:api_proto",
        "//google/iam/v1:v1_proto",
        "//google/type:type_proto",
        "@com_google_protobuf//:field_mask_proto",
    ],
)

go_proto_library(
    name = "iampb_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/iam/apiv1/iampb",
    proto = ":iampb_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//google/api:annotations_proto",
        "//google/api:client_proto",
        "//google/api:field_behavior_proto",
        "//google/api:resource_proto",
        "//google/iam/v1:options_proto",
        "//google/iam/v1:policy_proto",
        "//google/type:expr_proto",
    ],
)

go_library(
    name = "iampb",
    embed = [":iampb_go_proto"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/iam/apiv1/iampb",
    visibility = ["//visibility:public"],
)
