load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "900-EventsBridge_lib",
    srcs = ["main.go"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/20000-Context-Bridges/900-EventsBridge",
    visibility = ["//visibility:private"],
    deps = [
        "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/140-MCPBridge",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/events",
        "@com_connectrpc_connect//:connect",
        "@com_github_mark3labs_mcp_go//mcp",
    ],
)

go_binary(
    name = "900-EventsBridge",
    embed = [":900-EventsBridge_lib"],
    visibility = ["//visibility:public"],
)
