load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "900-AnalyticManager_lib",
    srcs = ["main.go"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/10000-Autonomous-Actors/900-AnalyticManager",
    visibility = ["//visibility:private"],
    deps = [
        "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/220-Whisper",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
        "//00SDLC/OlympusGCP/gen/olympus/analytic/v1/analyticv1connect",
        "@com_connectrpc_connect//:connect",
        "@com_github_lib_pq//:go_default_library",
        "@com_github_moby_moby_client//:go_default_library",
        "@com_github_redis_go_redis_v9//:go_default_library",
        "@org_golang_google_api//iterator",
        "@org_golang_google_api//option",
        "@org_golang_x_net//http2",
        "@org_golang_x_net//http2/h2c",
    ],
)

go_binary(
    name = "900-AnalyticManager",
    embed = [":900-AnalyticManager_lib"],
    visibility = ["//visibility:public"],
)
