load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "intelligencev1_proto",
    srcs = ["intelligence.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "intelligencev1_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/intelligence",
    proto = ":intelligencev1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "intelligence",
    embed = [":intelligencev1_go_proto"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/intelligence",
    visibility = ["//visibility:public"],
)
