load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "events",
    srcs = ["events.pb.go"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/connect-rpc/events/v1",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//reflect/protoreflect",
        "@org_golang_google_protobuf//runtime/protoimpl",
    ],
)
