load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "computepb_proto",
    srcs = ["compute.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:api_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/cloud:cloud_proto",
        "@com_google_protobuf//:any_proto",
    ],
)

go_proto_library(
    name = "computepb_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/google/cloud/compute/apiv1/computepb",
    proto = ":computepb_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:annotations_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:client_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:field_behavior_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:resource_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/cloud:extended_operations_proto",
    ],
)

go_library(
    name = "computepb",
    embed = [":computepb_go_proto"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/google/cloud/compute/apiv1/computepb",
    visibility = ["//visibility:public"],
)
