load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "900-Orchestrator_lib",
    srcs = ["main.go"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/10000-Autonomous-Actors/900-Orchestrator",
    visibility = ["//visibility:private"],
    deps = [
        "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/220-Whisper",
        "//00SDLC/OlympusGCP/gen/olympus/orchestration/v1/orchestrationv1connect",
        "@com_connectrpc_connect//:connect",
        "@com_github_robfig_cron_v3//:cron",
        "@org_golang_google_api//option",
        "@org_golang_x_net//http2",
        "@org_golang_x_net//http2/h2c",
    ],
)

go_binary(
    name = "900-Orchestrator",
    embed = [":900-Orchestrator_lib"],
    visibility = ["//visibility:public"],
)
