load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "finops",
    srcs = ["finops.pb.go"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/connect-rpc/finops/v1",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//reflect/protoreflect:go_default_library",
        "@org_golang_google_protobuf//runtime/protoimpl:go_default_library",
    ],
)
