load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "ObservabilityManager_lib",
    srcs = ["main.go"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/10000-Autonomous-Actors/ObservabilityManager",
    visibility = ["//visibility:private"],
    deps = [
        "//00SDLC/OlympusGCP/10000-Autonomous-Actors/10700-Processing-Engines/10710-Reasoning-Inference/inference",
        "@org_golang_x_net//http2:go_default_library",
        "@org_golang_x_net//http2/h2c:go_default_library",
    ],
)

go_binary(
    name = "ObservabilityManager",
    embed = [":ObservabilityManager_lib"],
    visibility = ["//visibility:public"],
)

go_test(
    name = "ObservabilityManager_test",
    srcs = ["main_test.go"],
    embed = [":ObservabilityManager_lib"],
    deps = [
        "//00SDLC/OlympusGCP/10000-Autonomous-Actors/10700-Processing-Engines/10710-Reasoning-Inference/inference",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/observability",
        "@com_connectrpc_connect//:go_default_library",
    ],
)
