load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "inference",
    srcs = [
        "compute.go",
        "data.go",
        "events.go",
        "finops.go",
        "firebase.go",
        "intelligence.go",
        "messaging.go",
        "observability.go",
        "storage.go",
        "vault.go",
    ],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/10000-Autonomous-Actors/10700-Processing-Engines/10710-Reasoning-Inference/inference",
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/compute",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/events",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/finops",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/firebase",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/intelligence",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/messaging",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/observability",
        "@com_connectrpc_connect//:connect",
        "@com_google_cloud_go//cloudtasks/apiv2/cloudtaskspb",
        "@io_etcd_go_bbolt//:go_default_library",
        "@org_golang_google_genproto//googleapis/iam/v1:iam",
        "@org_golang_google_protobuf//types/known/emptypb",
    ] + select({
        "@io_bazel_rules_go//go/platform:386": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:amd64": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:arm": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:arm64": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:mips": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:mips64": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:mips64le": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:mipsle": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:ppc64": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:ppc64le": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:riscv64": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "@io_bazel_rules_go//go/platform:s390x": [
            "//00SDLC/Olympus2/90000-Enablement-Labs/90200-Logic-Libraries/170-Policy",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
            "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        ],
        "//conditions:default": [],
    }),
)

go_test(
    name = "inference_test",
    srcs = [
        "compute_test.go",
        "data_test.go",
        "events_test.go",
        "finops_test.go",
        "firebase_test.go",
        "intelligence_test.go",
        "messaging_test.go",
        "observability_test.go",
        "storage_test.go",
        "vault_test.go",
    ],
    embed = [":inference"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/compute",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/data",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/events",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/finops",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/firebase",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/intelligence",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/messaging",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/observability",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/storage",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/40400-Protocol-Synthetics/protobuf/proto/v1/vault",
        "@com_connectrpc_connect//:connect",
    ],
)
