load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "eventsv1_proto",
    srcs = ["events.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "eventsv1_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/events",
    proto = ":eventsv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "events",
    embed = [":eventsv1_go_proto"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/events",
    visibility = ["//visibility:public"],
)
