load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "tasksv1_proto",
    srcs = ["tasks.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "tasksv1_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/olympus/tasks/v1",
    proto = ":tasksv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "tasks",
    embed = [":tasksv1_go_proto"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/olympus/tasks/v1",
    visibility = ["//visibility:public"],
)
