load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "longrunningpb_proto",
    srcs = ["operations.proto"],
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:api_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/rpc:rpc_proto",
        "@com_google_protobuf//:any_proto",
        "@com_google_protobuf//:descriptor_proto",
        "@com_google_protobuf//:duration_proto",
        "@com_google_protobuf//:empty_proto",
    ],
)

go_proto_library(
    name = "longrunningpb_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/longrunning/autogen/longrunningpb",
    proto = ":longrunningpb_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:annotations_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:client_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/api:field_behavior_proto",
        "//00SDLC/OlympusGCP/40000-Communication-Contracts/proto/google/rpc:status_proto",
    ],
)

go_library(
    name = "longrunningpb",
    embed = [":longrunningpb_go_proto"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/longrunning/autogen/longrunningpb",
    visibility = ["//visibility:public"],
)
