load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "analyticv1_proto",
    srcs = ["analytic.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "analyticv1_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/olympus/analytic/v1",
    proto = ":analyticv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "analytic",
    embed = [":analyticv1_go_proto"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/olympus/analytic/v1",
    visibility = ["//visibility:public"],
)
