load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "timeofday_proto",
    srcs = [
        "calendar_period.proto",
        "color.proto",
        "date.proto",
        "datetime.proto",
        "dayofweek.proto",
        "decimal.proto",
        "expr.proto",
        "fraction.proto",
        "interval.proto",
        "latlng.proto",
        "localized_text.proto",
        "money.proto",
        "month.proto",
        "phone_number.proto",
        "postal_address.proto",
        "quaternion.proto",
        "timeofday.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_protobuf//:duration_proto",
        "@com_google_protobuf//:timestamp_proto",
        "@com_google_protobuf//:wrappers_proto",
    ],
)

go_proto_library(
    name = "timeofday_go_proto",
    importpath = "google.golang.org/genproto/googleapis/type/timeofday",
    proto = ":timeofday_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "timeofday",
    embed = [":timeofday_go_proto"],
    importpath = "google.golang.org/genproto/googleapis/type/timeofday",
    visibility = ["//visibility:public"],
)
