load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "orchestrationv1_proto",
    srcs = ["orchestration.proto"],
    visibility = ["//visibility:public"],
)

go_proto_library(
    name = "orchestrationv1_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/olympus/orchestration/v1",
    proto = ":orchestrationv1_proto",
    visibility = ["//visibility:public"],
)

go_library(
    name = "orchestration",
    embed = [":orchestrationv1_go_proto"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/olympus/orchestration/v1",
    visibility = ["//visibility:public"],
)
