load("@io_bazel_rules_go//go:def.bzl", "go_library")
load("@io_bazel_rules_go//proto:def.bzl", "go_proto_library")
load("@rules_proto//proto:defs.bzl", "proto_library")

proto_library(
    name = "pubsubpb_proto",
    srcs = [
        "pubsub.proto",
        "schema.proto",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//google/api:api_proto",
        "//google/pubsub/v1:v1_proto",
        "@com_google_protobuf//:duration_proto",
        "@com_google_protobuf//:empty_proto",
        "@com_google_protobuf//:field_mask_proto",
        "@com_google_protobuf//:struct_proto",
        "@com_google_protobuf//:timestamp_proto",
    ],
)

go_proto_library(
    name = "pubsubpb_go_proto",
    compilers = ["@io_bazel_rules_go//proto:go_grpc"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/pubsub/v2/apiv1/pubsubpb",
    proto = ":pubsubpb_proto",
    visibility = ["//visibility:public"],
    deps = [
        "//google/api:annotations_proto",
        "//google/api:client_proto",
        "//google/api:field_behavior_proto",
        "//google/api:resource_proto",
        "//google/pubsub/v1:schema_proto",
    ],
)

go_library(
    name = "pubsubpb",
    embed = [":pubsubpb_go_proto"],
    importpath = "olympus.fleet/00SDLC/OlympusGCP/gen/pubsub/v2/apiv1/pubsubpb",
    visibility = ["//visibility:public"],
)
